export default {
    avatar: require("../assets/images/avatar.png"),
    cake1: require("../assets/images/cake1.png"),
    burgers: require("../assets/images/burgers.png"),
    fries: require("../assets/images/fries.png"),
    drinks: require("../assets/images/drinks.png"),
    hot_dog: require("../assets/images/hot_dog.png"),
    img_details: require("../assets/images/img_details.png"),
    cheese: require("../assets/images/cheese.png"),
    bacon: require("../assets/images/bacon.png"),
    onion: require("../assets/images/onion.png"),
    cart1: require("../assets/images/cart1.png"),
    cart2: require("../assets/images/cart2.png"),
    cart3: require("../assets/images/cart3.png"),
    cart4: require("../assets/images/cart4.png"),
    drink2: require("../assets/images/drink2.png"),
    drink3: require("../assets/images/drink3.png"),
    icream: require("../assets/images/icream.png"),
}